In [4]:
import numpy as np
minha_list = [1,2,3,4];
array_numpy = np.array(minha_list);
print(array_numpy);

[1 2 3 4]


In [6]:
minha_matriz = [[1,2,3],[6,5,4],[9,8,7]]
matriz_numpy = np.array(minha_matriz);
print(matriz_numpy)

[[1 2 3]
 [6 5 4]
 [9 8 7]]


In [15]:
matriz_auxiliar = np.arange(10,250,2) #inica em 10 até 249 de dois em dois
vetor_auxiliarZeros = np.zeros(12)
print(vetor_auxiliarZeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
matriz_auxiliarZeros = np.zeros((2,2))
print(matriz_auxiliarZeros)

[[0. 0.]
 [0. 0.]]


In [18]:
matriz_auxiliarZeros = np.ones((2,2))
print(matriz_auxiliarZeros)

[[1. 1.]
 [1. 1.]]


In [21]:
matriz_identidade = np.eye(3)
print(matriz_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
array = np.linspace(0,20,3) #numeros igualmente espacados
print(array)

[ 0. 10. 20.]


In [27]:
np.random.rand(5) * 100 

array([95.48393654, 80.26841637,  3.6443684 , 66.96305215, 29.51533623])

In [28]:
np.random.rand(2,5) * 100 #ou usa com randn

array([[26.63765408, 36.2145721 , 94.96018837, 23.89519206, 61.05992479],
       [21.01303525, 16.68093408, 23.57600598, 56.93503328, 27.36825343]])

In [36]:
np.random.randint(0,100,100) #

array([31, 99, 90, 24, 28, 76, 91, 95, 45, 74, 13, 37, 80,  5, 52, 40, 40,
       89, 92, 76, 61, 45, 31, 76, 85, 56, 45, 77, 82,  5,  2, 81, 60, 78,
       22, 61,  5, 97, 78,  6,  3, 32, 80, 10, 10, 33, 62, 39, 57, 54, 22,
       80, 35, 50, 33, 33, 93,  3, 98, 95, 32, 57,  6, 44,  3, 95,  9, 94,
        6, 30, 24, 15, 85, 44, 46, 57, 61, 90, 45, 25, 47, 17, 17, 58, 37,
       85, 73, 44, 18, 79, 64, 37, 19, 63, 32, 22, 28, 67, 56, 37])

In [38]:
np.round(np.random.rand(5)*100,0) # transformar para inteiro

array([78., 38., 66., 66., 36.])

In [48]:
array = np.random.rand(25) 
array = array.reshape((5,5)) #convertendo array para matriz
print(array)
print(array.shape) #atributo
print(array.max())
print(array.min())
print(array.argmax()) #indice do maior elemento
print(array.argmin()) #indice do menor elemento

[[0.258334   0.38938034 0.14639145 0.50686531 0.06454304]
 [0.54100227 0.40534566 0.84434641 0.68313954 0.60959886]
 [0.24989369 0.63040606 0.76618505 0.61747074 0.16153139]
 [0.35046142 0.92943172 0.23610768 0.61129732 0.86274194]
 [0.74011995 0.791541   0.61474429 0.21918546 0.935999  ]]
(5, 5)
0.9359990049331518
0.06454303625268532
24
4


In [54]:
array = np.round(np.random.rand(5)*100,0) # transformar para inteiro
print(array)
print(array[2:])

[61. 39. 29. 27. 68.]
[29. 27. 68.]


In [88]:
matriz = np.arange(50).reshape((5,10))
print(matriz)
print("________________________________")


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
________________________________


In [89]:
matriz2 = matriz[:3, 1:4]

In [90]:
print(matriz2);
matriz2[:] = 1100;
print(matriz2);
print(matriz);

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]
[[1100 1100 1100]
 [1100 1100 1100]
 [1100 1100 1100]]
[[   0 1100 1100 1100    4    5    6    7    8    9]
 [  10 1100 1100 1100   14   15   16   17   18   19]
 [  20 1100 1100 1100   24   25   26   27   28   29]
 [  30   31   32   33   34   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49]]


In [92]:
matriz3 = matriz[:3, 1:4].copy()
print(matriz3);
matriz3[:] = 200;
print(matriz3);
print(matriz);

[[1100 1100 1100]
 [1100 1100 1100]
 [1100 1100 1100]]
[[200 200 200]
 [200 200 200]
 [200 200 200]]
[[   0 1100 1100 1100    4    5    6    7    8    9]
 [  10 1100 1100 1100   14   15   16   17   18   19]
 [  20 1100 1100 1100   24   25   26   27   28   29]
 [  30   31   32   33   34   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49]]


In [100]:
print(matriz > 50);
bol = matriz > 50
print(matriz[bol].reshape(3,3))
print(1/matriz[bol].reshape(3,3))
print(np.sqrt(matriz[bol].reshape(3,3)))
print(matriz.std())
print(matriz.sum(axis=0)) #soma coluna da matrix
print(matriz.sum(axis=1)) #soma linhas da matrix

[[False  True  True  True False False False False False False]
 [False  True  True  True False False False False False False]
 [False  True  True  True False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]
[[1100 1100 1100]
 [1100 1100 1100]
 [1100 1100 1100]]
[[0.00090909 0.00090909 0.00090909]
 [0.00090909 0.00090909 0.00090909]
 [0.00090909 0.00090909 0.00090909]]
[[33.1662479 33.1662479 33.1662479]
 [33.1662479 33.1662479 33.1662479]
 [33.1662479 33.1662479 33.1662479]]
412.3357180744836
[ 100 3372 3374 3376  120  125  130  135  140  145]
[3339 3409 3479  345  445]
